// Mocks generated by Mockito 5.4.6 from annotations
// in pokemon_app/test/mock_providers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:domain/favorite_pokemon_use_case.dart' as _i3;
import 'package:domain/get_all_pokemon_use_case.dart' as _i5;
import 'package:domain/get_pokemon_ability_use_case.dart' as _i12;
import 'package:domain/get_pokemon_info_use_case.dart' as _i7;
import 'package:domain/get_pokemon_species_use_case.dart' as _i8;
import 'package:domain/get_pokemon_type_info_use_case.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:models/pokemon/info/pokemon_abalities.dart' as _i13;
import 'package:models/pokemon/info/pokemon_damage_relations.dart' as _i11;
import 'package:models/pokemon/info/pokemon_info.dart' as _i2;
import 'package:models/pokemon/info/pokemon_species.dart' as _i9;
import 'package:models/pokemon/pokemon_list_response.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemon_0 extends _i1.SmartFake implements _i2.Pokemon {
  _FakePokemon_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FavoritePokemonUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritePokemonUseCase extends _i1.Mock
    implements _i3.FavoritePokemonUseCase {
  MockFavoritePokemonUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Pokemon> saveInStorage(
    _i2.Pokemon? request, [
    Map<dynamic, dynamic>? args,
    bool? useDebounce,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveInStorage,
          [
            request,
            args,
            useDebounce,
          ],
        ),
        returnValue: _i4.Future<_i2.Pokemon>.value(_FakePokemon_0(
          this,
          Invocation.method(
            #saveInStorage,
            [
              request,
              args,
              useDebounce,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Pokemon>);

  @override
  _i4.Stream<List<_i2.Pokemon>> streamAll([Map<dynamic, dynamic>? args]) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamAll,
          [args],
        ),
        returnValue: _i4.Stream<List<_i2.Pokemon>>.empty(),
      ) as _i4.Stream<List<_i2.Pokemon>>);

  @override
  _i4.Future<dynamic> deleteInStorage(
    String? id, [
    Map<String, dynamic>? params,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteInStorage,
          [
            id,
            params,
          ],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);
}

/// A class which mocks [GetAllPokemonUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllPokemonUseCase extends _i1.Mock
    implements _i5.GetAllPokemonUseCase {
  MockGetAllPokemonUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i6.PokemonListResponse?> get([Map<dynamic, dynamic>? args]) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [args],
        ),
        returnValue: _i4.Future<_i6.PokemonListResponse?>.value(),
      ) as _i4.Future<_i6.PokemonListResponse?>);
}

/// A class which mocks [GetPokemonInfoUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPokemonInfoUseCase extends _i1.Mock
    implements _i7.GetPokemonInfoUseCase {
  MockGetPokemonInfoUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Pokemon?> get([Map<dynamic, dynamic>? args]) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [args],
        ),
        returnValue: _i4.Future<_i2.Pokemon?>.value(),
      ) as _i4.Future<_i2.Pokemon?>);
}

/// A class which mocks [GetPokemonSpeciesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPokemonSpeciesUseCase extends _i1.Mock
    implements _i8.GetPokemonSpeciesUseCase {
  MockGetPokemonSpeciesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i9.Species?> get([Map<dynamic, dynamic>? args]) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [args],
        ),
        returnValue: _i4.Future<_i9.Species?>.value(),
      ) as _i4.Future<_i9.Species?>);
}

/// A class which mocks [GetPokemonTypeInfoUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPokemonTypeInfoUseCase extends _i1.Mock
    implements _i10.GetPokemonTypeInfoUseCase {
  MockGetPokemonTypeInfoUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i11.DamageRelations?> get([Map<dynamic, dynamic>? args]) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [args],
        ),
        returnValue: _i4.Future<_i11.DamageRelations?>.value(),
      ) as _i4.Future<_i11.DamageRelations?>);
}

/// A class which mocks [GetPokemonAbilityUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPokemonAbilityUseCase extends _i1.Mock
    implements _i12.GetPokemonAbilityUseCase {
  MockGetPokemonAbilityUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i13.AbilityInfo?> get([Map<dynamic, dynamic>? args]) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [args],
        ),
        returnValue: _i4.Future<_i13.AbilityInfo?>.value(),
      ) as _i4.Future<_i13.AbilityInfo?>);
}
